# Generated by Django 3.2.8 on 2021-10-23 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_book_yearpublished'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='yearpublished',
            field=models.CharField(default='', max_length=50),
        ),
    ]
