# Generated by Django 3.2.8 on 2021-10-23 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_book_yearpublished'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='yearpublished',
            new_name='year_published',
        ),
    ]
