# Generated by Django 3.2.8 on 2021-10-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_yearpublished_book_year_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='Super_AdminAccount',
            fields=[
                ('SId', models.AutoField(primary_key=True, serialize=False)),
                ('Fname', models.CharField(default='First Name', max_length=255)),
                ('Lname', models.CharField(default='Last Name', max_length=255)),
                ('Email', models.EmailField(default='Email Name', max_length=255)),
                ('Username', models.CharField(default='Username ', max_length=255)),
                ('Password', models.TextField(default='Password ', max_length=3000)),
                ('ContactNo', models.CharField(default='Contact no', max_length=100)),
            ],
        ),
    ]
