# Generated by Django 3.2.8 on 2021-10-28 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_super_adminaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Super_Admin_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.super_adminaccount'),
        ),
    ]
